config/routes.rb
SampleApp::Application.routes.draw do
  
  scope "(:locale)", locale: /en|es/ do
    match '/help',    to: 'static_pages#help'
    match '/about',   to: 'static_pages#about'
    match '/contact', to: 'static_pages#contact'
    match '/signup',  to: 'users#new'
    match '/signin',  to: 'sessions#new'
    match '/signout', to: 'sessions#destroy', via: :delete
    
    resources :users
    resources :sessions, only: [:new, :create, :destroy]
  
    root to: 'static_pages#home'
  end
  
  match /en|es/, to: 'static_pages#home'

  
  
  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer         not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#  password_digest :string(255)
#  remember_token  :string(255)
#  admin           :boolean         default(FALSE)
#

class User < ActiveRecord::Base
  has_secure_password
  
  attr_accessible :email, :name, :password, :password_confirmation
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name,                  presence: true, length: { maximum: 50 }
  validates :email,                 presence: true, format: { with: VALID_EMAIL_REGEX },
                                    uniqueness: { case_sensitive: false }
  validates :password,              length: { minimum: 6 }
  validates :password_confirmation, presence: true
  
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  
private
  
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
  
  before_filter :set_locale
  
  def default_url_options(options={})
    logger.debug "default_url_options is passed options: #{options.inspect}\n"
    { :locale => I18n.locale }
  end
  
private
  
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    build_error_message(params)
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      redirect_to signin_path, flash: { error: @error_message.join('. ') }
    end
  end
  
  def destroy
    sign_out
    redirect_to root_path
  end

private

  def build_error_message(params)
    @error_message = []
    case
    when params[:session][:email].blank?
      @error_message << "An email is required to login"
    when params[:session][:password].blank?
      @error_message << "A password is required to login"
    when !User.exists?(email: params[:session][:email])
      @error_message << "It doesn't look like that email is registered yet. Perhaps you meant to sign up instead?"
    end
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :redirect_signed_in_user, only: [:new, :create]
  before_filter :require_sign_in,         only: [:index, :edit, :update, :destroy]
  before_filter :correct_user,            only: [:edit, :update]
  before_filter :admin_user,              only: :destroy
  
  def index
    @users = User.order('name ASC').paginate(page: params[:page]).all
  end
  
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      redirect_to @user, flash: { success: 'Welcome to the Sample App!' }
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(params[:user])
      sign_in @user
      redirect_to @user, flash: { success: "Profile updated" }
    else
      render :edit
    end
  end
  
  def destroy
    user = User.find(params[:id])
    if current_user?(user)
      redirect_to user, alert: "You cannot remove your own account"
    else
      user.destroy
      redirect_to users_path, flash: { success: 'User has been deleted' }
    end
  end

private

  def require_sign_in
    if not signed_in?
      store_location
      redirect_to signin_path, notice: "Please sign in."
    end
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path if not current_user?(@user)
  end
  
  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end
  
  def redirect_signed_in_user
    if signed_in?
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    page_title.present? ? "#{base_title} | #{page_title}" : base_title
  end
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    current_user = user
  end
  
  def sign_out
    current_user = nil
    cookies.delete(:remember_token)
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= user_from_remember_token
  end
  
  def current_user?(user)
    user == @current_user
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end
  
  def store_location
    session[:return_to] = request.fullpath
  end

private
  
  def user_from_remember_token
    remember_token = cookies[:remember_token]
    User.find_by_remember_token(remember_token) unless remember_token.nil?
  end
  
  def clear_return_to
    session.delete(:return_to)
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, *args)
    opts = args.extract_options!
    opts[:size] ||= 90
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{opts[:size]}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
  
end

app/views/layouts/_flash_messages.html.erb
<%- flash.each do |kee, val| -%>
  <%= content_tag :div, val, class: %Q{alert alert-#{kee}} %>
<%- end -%>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class='navbar navbar-fixed-top'>
  <div class='navbar-inner'>
    <div class='container'>
      <%= link_to "sample app", root_path, id: "logo" %>
      <nav>
        <ul class='nav pull-right'>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          
          <%- if signed_in? -%>
            <li><%= link_to 'Users', users_path %></li>
            <li id='fat-menu' class='dropdown'>
              <a href='#' class='dropdown-toggle' data-toggle='dropdown'>
                Account <b class='caret'></b>
              </a>
              <ul class='dropdown-menu'>
                <li><%= link_to 'Profile', current_user %></li>
                <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
                <li class='divider'></li>
                <li>
                  <%= link_to 'Sign out', signout_path, method: :delete %>
                </li>
              </ul>
            </li>
          <%- else -%>
            <li><%= link_to 'Sign in', signin_path %></li>
          <%- end -%>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_ie-shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/ie-shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class='container'>
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%- if Rails.env.development? -%>
    <div id='debug'>
      <%= debug(params) if Rails.env.development? %>
    </div>
    <%- end -%>
  </div>

  <!-- Scripts after this line -->
</body>
</html>

app/views/shared/_error_messages.html.erb
<%- if @user.errors.any? -%>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, 'error') %>.
    </div>
    <ul>
      <%- @user.errors.full_messages.each do |msg| -%>
      <li>* <%= msg %></li>
      <%- end -%>
    </ul>
  </div>
<%- end -%>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>
<h1>Contact Us</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<div class='center hero-unit'>
  <h1>Welcome to the Sample App</h1>
  
  <h2>
    This is the home page for the <%= link_to "Ruby on Rails Tutorial", "http://railstutorial.org/" %>
    sample application.
  </h2>
  
  <%= link_to "Sign up now!", signup_path, class: 'btn btn-large btn-primary' %>
</div>

<%= link_to image_tag('rails.png', alt: 'Ruby on Rails'), 'http://rubyonrails.org/' %>

app/views/users/_form.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= simple_form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= yield f %>
    <% end %>
    
    <%- unless @user.new_record? -%>
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target='_blank'>change</a>
    <%- end -%>
  </div>
</div>

app/views/users/_user.html.erb
<%= content_tag_for :li, user do %>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <%- if current_user.admin? && !current_user?(user) -%>
    | <%= link_to 'delete', user, method: :delete, confirm: "Are you sure?" %>
  <%- end -%>
<%- end -%>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> 
<h1>Update your profile</h1>

<%= render layout: 'form' do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation, label: 'Confirm Password' %>
  <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
<%- end -%>

app/views/users/index.html.erb
<%= provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class='users'>
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<%- provide :title, t('forms.users.new.title') -%>
<h1><%= t('forms.users.new.title') %></h1>

<%= render layout: 'form' do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.button :wrapped, cancel: root_path, value: t('forms.users.new.button') %>
<%- end -%>

app/views/users/show.html.erb
<%- provide :title, @user.name -%>
<div class='row'>
  <aside class='span4'>
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>